### ISSUE TITLE
Group Kansan Submission

### ISSUE THREAD

**Issue by CRClothier** [miftah1991/space-travelers#47]
Here is the link to our Kansan board:

https://github.com/miftah1991/space-travelers/projects/2

We are a group of 3 people.

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @CRClothier, @miftah1991 and @eng-mohamed-eldeeb,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
